spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fd06
    username: root
    password: root
   
  jpa:
   hibernate:
      ddl-auto: update
    
    